# This workflow will build the source code and run dynamic tests using Nuclei

name: Nuclei Dynamic Security Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build project with Node.js 16s
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0
    - run: docker-compose up --build --detach
    - run: curl http://127.0.0.1:8080/
        
    # - name: Run Nuclei
    #   uses: projectdiscovery/nuclei-action@main
    #   with:
    #     target: "http://127.0.0.1:3000"

    # - name: GitHub Security Dashboard Alerts update
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: nuclei.sarif
